const data = {
    nameUser: 'jdias-mo',//  jdias-mo gfreitas
    paramsEx00: [{dest: 'ola', src: 'mundo'},{dest: 'raposa', src: 'mbunda'},{dest: '42Lis', src: '42'}],
    paramsEx01: [{dest: 'ola', src: 'mundo', int: 3},
    {dest: 'ola', src: 'mundo', int: 3},
    {dest: 'amigo', src: 'friend', int: 8},
    {dest: 'programa', src: 'toi', int: 8}],
    paramsEx02: ['ABSbffdkj', 'ifie90}', 'hgf8', 983457394, 'AS[BVG', 'kl\ssk',
    'gtgtG', 'gt*', 'pijh^'],
    paramsEx03: [
        '129090039',
        '1290909:',
        "giojoi64;",
        983457394,
        'AS[BVG234',
        'kl\ssk',
        'gtgtG',
        'gt*',
        'pijh^'],
    paramsEx04: [
        '129090039',
        'hiueuyqaazznjkg:',
        'hiueuyqaazznjkg',
        "hjjazhA",
        983457394,
        'AS[BVG234',
        '$%^$',
        'gtgtG',
        'gt*',
        'pijh^'],
        paramsEx05: [
        'AAA@',
        'ABHFBBETZ:',
        'ABHFBBETZ',
        'ABHF[',
        'ABHF}',
        'AF\}',
        'AAIJID^',
        'AAIJIDa'],
        paramsEx06: [
        "'\n'",
        'ABHFBBETZ:',
        "ABHFBBETZ",
        'ABHF[',
        'ABHF}',
        'AF\}',
        'AAIJID^ ',
        // "\n",
        'AAIJIDa'],
        paramsEx07: [
        "abcdca",
        'ABCFST:',
        "abvcAA",
        'ABHF[',
        'ABHF}',
        'AAIAbb',
        'AIDa2'],
        paramsEx08: [
        "abcdca",
        'ABCFST:',
        "abvcAA",
        'ABHF[',
        'AbHF}',
        'AAIAbb',
        'AIDa2'],
        paramsEx09: [
        "Ola mundo, o mundo esta ola",
        'E voce? como vai seu DIA..',
        "Teste que testa Bem TesT_ADo serA",
        'heLLo'],
        paramsEx10: [
        {dest: 'alo', src: 'mundo', int: 3},
        {dest: 'ola', src: 'alo', int: 3},
        {dest: 'amigo', src: 'friend', int: 5},
        {dest: 'programa', src: 'toi', int: 8}],
        paramsEx11: [
            "\n",
            'ABHFB\nBETZ: \n',
            "ABHFBBETZ",
            'nada',
            'ABHF} \0',
            'AF\}',
            'AAIJID^/n'
        ],
        paramsEx12: [{addr: 'ola', size: 'mundo'},{addr: 'ola', size: 'mundo'},{addr: 'ola', size: 'mundo'}],
};
module.exports = { data };
